Repository Romantic-Yeojido/frontend, pull requests merged in 2024-12, with the labels that each got.

#5 Feat: 지도화면 UI 구현 (#3)
  .idea/misc.xml
  app/src/main/res/drawable/bg_mapbutton.xml
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_circle_plus_btn.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_mappopup.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#10 Feat: symbol 추가
  app/src/main/res/drawable/ic_symbol.xml
Labels: ✨ Feature

#12 Feat: icon 추가
  app/src/main/res/drawable/ic_icon_black_img.png
  app/src/main/res/drawable/ic_icon_white_img.png
Labels: ✨ Feature

#15 "Feat: 폰트색상추가"
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/values/colors.xml
Labels: ✨ Feature

#18 Feat: Gradle 바인딩 추가가
  app/build.gradle
Labels: ✨ Feature

#19 Fix/#16 지도화면UI수정
  app/src/main/res/drawable/bg_mapbutton.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/item_mappopup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 BugFix

#25 Feat: 추억 등록하기 UI 구현(#13)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/romanticyeojido/MainActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/MapActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/memoryPost/MemoryPostActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/memoryPost/SpinnerAdapter.kt
  app/src/main/res/drawable/bg_register_btn_active.xml
  app/src/main/res/drawable/bg_register_btn_default.xml
  app/src/main/res/drawable/bg_spinner_active.xml
  app/src/main/res/drawable/bg_spinner_default.xml
  app/src/main/res/drawable/bg_spinner_dropdown.xml
  app/src/main/res/drawable/edittext_custom.xml
  app/src/main/res/drawable/edittext_default.xml
  app/src/main/res/drawable/edittext_error.xml
  app/src/main/res/drawable/edittext_focused.xml
  app/src/main/res/drawable/edittext_selector.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_img_post.xml
  app/src/main/res/drawable/spinner_dropdown_selector.xml
  app/src/main/res/drawable/spinner_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_memory_post.xml
  app/src/main/res/layout/item_spinner_active.xml
  app/src/main/res/layout/item_spinner_default.xml
  app/src/main/res/layout/item_spinner_dropdown.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ Feature

#44 Feat: 지도 핀 설정 초기세팅 (#43)
  app/src/main/java/com/example/romanticyeojido/ui/map/MapActivity.kt
  app/src/main/res/drawable/ic_pin.png
Labels: ✨ Feature

#53 Feat: api 초기 세팅 (#52)
  app/build.gradle
  app/src/main/java/com/example/romanticyeojido/network/NetworkModule.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/MapActivity.kt
Labels: ✨ Feature

#57 Feat: 네이버 소셜 로그인 초기 구현 (#56)
  .idea/deploymentTargetSelector.xml
  app/build.gradle
  app/src/main/java/com/example/romanticyeojido/MainActivity.kt
  app/src/main/java/com/example/romanticyeojido/SplashActivity.kt
  app/src/main/res/drawable/img_kakao_login_wide.png
  app/src/main/res/drawable/img_naver_login.png
  app/src/main/res/layout/activity_splash.xml
  gradle.properties
Labels: ✨ Feature

#59 Feat: 카카오 로그인 추가 (#56)
  app/build.gradle
  app/src/main/java/com/example/romanticyeojido/SplashActivity.kt
  app/src/main/java/com/example/romanticyeojido/network/UserInfoDialog.kt
  app/src/main/java/com/example/romanticyeojido/network/Utility.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_user_info.xml
Labels: ✨ Feature

#61 Feat: 저장위치 및 요약정보 수신 (#60)
  app/build.gradle
  app/src/main/java/com/example/romanticyeojido/network/MemoryInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/PinInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/PinResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/PopupResponse.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/MapActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/PopupActivity.kt
  app/src/main/res/drawable/ic_pin_gray.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#63 Fix: 로그인 버튼 디자인 수정 (#62)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/romanticyeojido/LocationTermActivity.kt
  app/src/main/java/com/example/romanticyeojido/MainActivity.kt
  app/src/main/java/com/example/romanticyeojido/PrivacyPolicyActivity.kt
  app/src/main/java/com/example/romanticyeojido/SettingsActivity.kt
  app/src/main/java/com/example/romanticyeojido/SplashActivity.kt
  app/src/main/java/com/example/romanticyeojido/TermsOfServiceActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/settings/LocationTermActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/settings/PrivacyPolicyActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/settings/SettingsActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/settings/TermsOfServiceActivity.kt
  app/src/main/res/drawable/img_kakao_login.png
  app/src/main/res/drawable/img_kakao_login_wide.png
  app/src/main/res/drawable/img_naver_login.png
  app/src/main/res/layout/activity_splash.xml
Labels: 🎨 Layout & Style

#66 Feat: 소셜 로그인 userId 값 설정 (#65)
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/romanticyeojido/MainActivity.kt
  app/src/main/java/com/example/romanticyeojido/SplashActivity.kt
  app/src/main/java/com/example/romanticyeojido/network/AuthResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/NaverAuthInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/NetworkModule.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/MapActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/PopupActivity.kt
Labels: ✨ Feature

#71 Fix: 소셜 로그인 userId값 오류 수정 (#70)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/romanticyeojido/MainActivity.kt
  app/src/main/java/com/example/romanticyeojido/SplashActivity.kt
  app/src/main/java/com/example/romanticyeojido/WebViewActivity.kt
  app/src/main/res/layout/activity_web_view.xml
Labels: 🐞 BugFix

#77 Feat: 추억 등록하기 API 연결 완료 (#67)
  app/src/main/java/com/example/romanticyeojido/PhotoGetActivity.kt
  app/src/main/java/com/example/romanticyeojido/PhotoPostActivity.kt
  app/src/main/java/com/example/romanticyeojido/SplashActivity.kt
  app/src/main/java/com/example/romanticyeojido/network/AuthResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/NetworkModule.kt
  app/src/main/java/com/example/romanticyeojido/network/locker/Photo.kt
  app/src/main/java/com/example/romanticyeojido/network/locker/PhotoInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/locker/PhotoPostUtility.kt
  app/src/main/java/com/example/romanticyeojido/network/map/NewpinInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/map/NewpinRequest.kt
  app/src/main/java/com/example/romanticyeojido/network/map/NewpinResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/map/PinInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/map/PinResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/map/PopupInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/map/PopupResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/memoryPost/MemoryInterface.kt
  app/src/main/java/com/example/romanticyeojido/network/memoryPost/MemoryService.kt
  app/src/main/java/com/example/romanticyeojido/network/socialLogin/AccessTokenManager.kt
  app/src/main/java/com/example/romanticyeojido/network/socialLogin/AuthResponse.kt
  app/src/main/java/com/example/romanticyeojido/network/socialLogin/NaverAuthInterface.kt
  app/src/main/java/com/example/romanticyeojido/ui/UserInfoDialog.kt
  app/src/main/java/com/example/romanticyeojido/ui/locker/PhotoPagerAdapter.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/MapActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/map/PopupActivity.kt
  app/src/main/java/com/example/romanticyeojido/ui/memoryPost/MemoryPostActivity.kt
  app/src/main/java/com/example/romanticyeojido/utils/ImageMultipart.kt
  app/src/main/java/com/example/romanticyeojido/utils/Utility.kt
  app/src/main/java/com/example/romanticyeojido/utils/getFile.kt
Labels: ✨ Feature, 📬 API
